project:
  type: website

website:
  description: "Notes on maths and other things."
  site-url: https://richardpmason.com
  title: "Richard Mason"
  navbar:
    right:
      - publications.qmd
      - about.qmd
      - icon: twitter-x
        href: https://x.com/richpmason
        aria-label: X
      - icon: github
        href: https://github.com/rpmason
      - icon: linkedin
        href: https://www.linkedin.com/in/richard-p-mason/
        aria-label: LinkedIn
format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    html-math-method: mathjax



